on: [push]

jobs:
  publish_docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Publish docs
        uses: docploy/docploy-action@main
        with:
          baseUrl: 'https://cvuong.github.io/test-action/'
          docsDir: 'docs'
  test_docs:
    name: Test docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn run jest docs
