on: [push]

jobs:
  publish_docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish docs
        uses: docploy/docploy-action@main
        with:
          baseUrl: 'https://cvuong.github.io/test-action/'
          docsDir: 'docs/'
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 180
    test_docs:
      name: Test docs
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Run doc tests
          run: yarn test docs
