on: [push]

jobs:
  publish_docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pubish docs
        uses: docploy/docploy-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workspace: ${{ env.GITHUB_WORKSPACE }}
